PLAT-425 Upgrade to Ruby 2.7.1
art19/url_validation pull request #3
Opened 2020-05-01 00:01 UTC by nakedsushi

https://art19co.atlassian.net/browse/PLAT-425

2020-05-13 23:26 UTC, johvet requested changes

2020-05-13 23:26 UTC, johvet commented on .rubocop.yml
> +  TargetRubyVersion: 2.6
2.7?

2020-05-13 23:26 UTC, johvet commented on .travis.yml
> +- 2.7.1
I'd maybe still suggest to build for 2.6.2

2020-05-13 23:26 UTC, johvet commented on README.textile
> +
since this is our fork now, do we like to add our travis badge on top (and how about cc integration).

2020-05-13 23:26 UTC, johvet commented on Rakefile
> +# frozen_string_literal: true
if this remains our fork and is disconnected from upstream, we might use our default Rakefile and have the yard stuff sit in a .yardopts

2020-05-13 23:26 UTC, johvet commented on lib/url_validation.rb
> +    return false unless Array.wrap(options[:scheme] || %w[http https]).include?(uri.try(:scheme))
`%w[http https]` could be a frozen const

2020-05-13 23:26 UTC, johvet commented on spec/spec_helper.rb
> -
this is empty? we don't throw in our regular rspec config

2020-05-13 23:26 UTC, johvet commented on url_validation.gemspec
> +  s.add_dependency 'activesupport', '~> 5.1.7'
shouldn't these be `>= 5.1.7` ?

2020-05-16 17:38 UTC, johvet requested changes
getting there :-)

2020-05-16 17:38 UTC, johvet commented on Gemfile.lock
> +      i18n (>= 0.7, < 2)
I think you need to limit the `activemodel` to the consisten `5.1.7` constraint. otherwise you bring in 6+ which yields quite some warning.

2020-05-18 17:03 UTC, johvet approved these changes

2020-05-18 17:03 UTC, johvet commented on lib/url_validation/version.rb
> +  VERSION = '1.1.2'
wouldn't this be `1.1.1` but I am not sure

2020-05-21 02:41 UTC, nakedsushi commented
Not gonna merge this into master since that might mess up the current rails app that's pointing to the master version. Instead, I've created an `art19-patched` branch for the rails app branch that has the ruby 2.7.1 upgrade work. https://github.com/art19/url_validation/tree/art19-patched

2020-05-21 02:41 UTC, closed without merging